version: '2'
linters:
  default: standard
  enable:
    - lll
  settings:
    lll:
      line-length: 80
      tab-width: 4
formatters:
  enable:
    - gofmt
    - golines
  settings:
    golines:
      max-len: 80
      tab-len: 4
