CREATE TYPE path_type AS ENUM ('web', 'file');

CREATE TABLE page (
  id bigint UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  path text PRIMARY KEY,
  type path_type NOT NULL,
  dict jsonb DEFAULT '{}' NOT NULL
);

INSERT INTO "page"("path", "type", "dict") values(
  '/some/path',
  'file',
  '{"key1": 1, "key2": 2}'
);

INSERT INTO "page"("path", "type", "dict") values(
  '/some/other/path',
  'file',
  '{"key2": 4, "key3": 6}'
);
