CREATE TYPE path_type AS ENUM ('web', 'file');
CREATE TYPE SOURCE_TYPE AS ENUM ('file', 'dir', 'url');

CREATE TABLE document (
  id bigint UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  path text PRIMARY KEY,
  type path_type NOT NULL,
  words jsonb DEFAULT '{}' NOT NULL
);

CREATE TABLE indexer (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  exec text NOT NULL,
  args jsonb DEFAULT '{}' NOT NULL
);

create TABLE collection (
  id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  path text NOT NULL,
  indexer_id bigint REFERENCES indexer(id),
  recursive boolean NOT NULL,
  source_type SOURCE_TYPE NOT NULL,
  respect_last_modified boolean NOT NULL,
  normalizer int not NULL
);
