CREATE TYPE path_type AS ENUM ('web', 'file');

CREATE TABLE document (
  id bigint UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  path text PRIMARY KEY,
  type path_type NOT NULL,
  words jsonb DEFAULT '{}' NOT NULL
);

CREATE TABLE texts (
    text_path text FOREIGN KEY REFERENCES document(path),
    plain_text text NOT NULL
);