CREATE TYPE path_type AS ENUM ('web', 'file');
CREATE TYPE SOURCE_TYPE AS ENUM ('file', 'dir', 'url');


CREATE TABLE indexer (
  id text PRIMARY KEY,
  name text NOT NULL,
  exec text NOT NULL,
  args jsonb DEFAULT '{}' NOT NULL,
  port int UNIQUE NOT NULL
);

CREATE TABLE collection (
  id text PRIMARY KEY,
  path text NOT NULL,
  indexer_id text REFERENCES indexer(id),
  recursive boolean NOT NULL,
  source_type SOURCE_TYPE NOT NULL,
  respect_last_modified boolean NOT NULL,
  normalizer int NOT NULL
);

CREATE TABLE document (
  id bigint UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  path text PRIMARY KEY,
  type path_type NOT NULL,
  words jsonb DEFAULT '{}' NOT NULL,
  last_indexed text NOT NULL,
  collection_id text REFERENCES collection(id)
);
